name: touga1
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# neu von mir eingefügt
http: ^0.15.0

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"



# environment:
#   sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
    
  flutter_riverpod: ^2.0.0
  cached_network_image: ^3.2.0

  dio: ^5.0.0
  flutter_secure_storage: ^8.0.0
  # Optional for animations
  animations: ^2.0.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  # HTML-basierter WYSIWYG-Editor
  #html_editor_enhanced: ^2.7.1
  # Rich-Text-Editor mit Flutter Quill
  flutter_quill: ^11.4.2
  flutter_quill_extensions: ^11.0.0
  vsc_quill_delta_to_html: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

